import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

enum categoryData {
  "和食",
  "洋食",
  "中華",
  "アジアン",
  "イタリアン",
  "フレンチ",
  "韓国料理",
  "その他",
  "スイーツ",
  "カフェ",
  "インド",
}

enum subCategoriesData {
  "丼物",
  "海鮮",
  "肉料理",
  "麺類",
  "ご飯",
  "鍋",
  "揚げ物",
  "サラダ",
  "スープ",
  "パスタ",
  "ピザ",
  "サンドイッチ",
  "甘い",
  "辛い",
  "酸っぱい",
  "苦い",
  "デザート",
}

const data: {
  name: string; // 料理名 例: かつ丼
  categoryName: string; // カテゴリ名 例: 和食
  subCategoriesNames: string[]; // サブカテゴリ名 例: 丼物, ご飯, 肉料理
  ingredientsNames: string[]; // 材料名 例: 豚肉, ご飯, タマネギ, 卵
}[] = [
  {
    name: "かつ丼",
    categoryName: "和食",
    subCategoriesNames: ["丼物", "ご飯", "肉料理"],
    ingredientsNames: ["豚肉", "ご飯", "タマネギ", "卵"],
  },
  {
    name: "カルボナーラ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ", "ピザ"],
    ingredientsNames: ["パスタ", "ベーコン", "卵黄", "生クリーム", "粉チーズ"],
  },
  {
    name: "タコライス",
    categoryName: "メキシコ料理",
    subCategoriesNames: ["ご飯", "肉料理"],
    ingredientsNames: ["豚肉", "ご飯", "タコス", "レタス", "トマト"],
  },
  {
    name: "親子丼",
    categoryName: "和食",
    subCategoriesNames: ["丼物", "ご飯", "肉料理"],
    ingredientsNames: ["鶏肉", "卵", "ご飯", "青ネギ"],
  },
  {
    name: "チキンカレー",
    categoryName: "インド",
    subCategoriesNames: ["鍋", "ご飯", "肉料理"],
    ingredientsNames: [
      "鶏肉",
      "ジャガイモ",
      "にんじん",
      "タマネギ",
      "カレー粉",
    ],
  },
  {
    name: "ナポリタン",
    categoryName: "洋食",
    subCategoriesNames: ["パスタ"],
    ingredientsNames: ["スパゲッティ", "玉ねぎ", "ハム", "トマトケチャップ"],
  },
  {
    name: "スパゲッティ・ボンゴレ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ", "ソース"],
    ingredientsNames: [
      "スパゲッティ",
      "ニンニク",
      "唐辛子",
      "オリーブオイル",
      "アサリ",
    ],
  },
  {
    name: "ローストビーフ",
    categoryName: "洋食",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: ["牛肉", "塩", "こしょう", "バター"],
  },
  {
    name: "麻婆豆腐",
    categoryName: "中華",
    subCategoriesNames: ["麺類", "ご飯"],
    ingredientsNames: [
      "絹ごし豆腐",
      "豚ひき肉",
      "豆板醤",
      "豆豉",
      "花椒",
      "豆板醤油",
      "醤油",
      "砂糖",
      "豆板醤の素",
    ],
  },
  {
    name: "カレーライス",
    categoryName: "和食",
    subCategoriesNames: ["ご飯"],
    ingredientsNames: [
      "カレールー",
      "玉ねぎ",
      "にんじん",
      "じゃがいも",
      "鶏肉",
    ],
  },
  {
    name: "ナポリタン",
    categoryName: "洋食",
    subCategoriesNames: ["パスタ"],
    ingredientsNames: [
      "スパゲッティ",
      "玉ねぎ",
      "ピーマン",
      "ウインナー",
      "ケチャップ",
    ],
  },
  {
    name: "エビチリ",
    categoryName: "中華",
    subCategoriesNames: ["鍋"],
    ingredientsNames: [
      "えび",
      "玉ねぎ",
      "にんにく",
      "しょうが",
      "豆板醤",
      "砂糖",
      "酢",
      "醤油",
    ],
  },
  {
    name: "餃子",
    categoryName: "中華",
    subCategoriesNames: ["揚げ物"],
    ingredientsNames: [
      "豚ひき肉",
      "キャベツ",
      "にら",
      "生姜",
      "醤油",
      "酢",
      "ごま油",
    ],
  },
  {
    name: "ナン",
    categoryName: "インド",
    subCategoriesNames: ["パン"],
    ingredientsNames: ["小麦粉", "水", "イースト", "塩", "砂糖"],
  },
  {
    name: "カルボナーラ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ"],
    ingredientsNames: [
      "パスタ",
      "ベーコン",
      "卵黄",
      "生クリーム",
      "パルメザンチーズ",
    ],
  },
  {
    name: "マルゲリータピザ",
    categoryName: "イタリアン",
    subCategoriesNames: ["ピザ"],
    ingredientsNames: [
      "トマトソース",
      "モッツァレラチーズ",
      "バジル",
      "オリーブオイル",
    ],
  },
  {
    name: "オムレツ",
    categoryName: "洋食",
    subCategoriesNames: ["卵料理"],
    ingredientsNames: ["卵", "牛乳", "バター", "塩", "こしょう"],
  },
  {
    name: "カキフライ",
    categoryName: "和食",
    subCategoriesNames: ["揚げ物", "海鮮"],
    ingredientsNames: ["カキ", "小麦粉", "パン粉", "卵"],
  },
  {
    name: "マグロ漬け丼",
    categoryName: "和食",
    subCategoriesNames: ["丼物", "海鮮", "ご飯"],
    ingredientsNames: ["マグロ", "しょうゆ", "酢", "みりん"],
  },
  {
    name: "ミートソーススパゲッティ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ", "肉料理"],
    ingredientsNames: ["挽肉", "玉ねぎ", "にんにく", "トマト"],
  },
  {
    name: "味噌ラーメン",
    categoryName: "中華",
    subCategoriesNames: ["麺類", "スープ"],
    ingredientsNames: ["麺", "豚肉", "もやし", "味噌"],
  },
  {
    name: "豚キムチ炒め",
    categoryName: "韓国料理",
    subCategoriesNames: ["肉料理", "鍋"],
    ingredientsNames: ["豚肉", "キムチ", "ニラ", "にんにく"],
  },
  {
    name: "パンケーキ",
    categoryName: "スイーツ",
    subCategoriesNames: ["甘い"],
    ingredientsNames: ["小麦粉", "卵", "牛乳", "砂糖"],
  },
  {
    name: "カレーライス",
    categoryName: "その他",
    subCategoriesNames: ["ご飯", "肉料理"],
    ingredientsNames: ["牛肉", "玉ねぎ", "ジャガイモ", "カレールー"],
  },
  {
    name: "クリームパスタ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ", "甘い"],
    ingredientsNames: ["生クリーム", "ベーコン", "パスタ", "玉ねぎ"],
  },
  {
    name: "餃子",
    categoryName: "中華",
    subCategoriesNames: ["揚げ物", "肉料理"],
    ingredientsNames: ["豚肉", "キャベツ", "ニンニク", "ショウガ"],
  },
  {
    name: "シーフードピザ",
    categoryName: "イタリアン",
    subCategoriesNames: ["ピザ", "海鮮"],
    ingredientsNames: ["トマトソース", "シーフード", "チーズ", "生地"],
  },
  {
    name: "バターチキンカレー",
    categoryName: "インド",
    subCategoriesNames: ["鍋", "スパイシー", "辛い", "ご飯"],
    ingredientsNames: ["鶏肉", "トマト", "玉ねぎ", "生クリーム", "スパイス"],
  },
  {
    name: "チキンカツサンドイッチ",
    categoryName: "カフェ",
    subCategoriesNames: ["サンドイッチ", "揚げ物"],
    ingredientsNames: [
      "チキンカツ",
      "食パン",
      "レタス",
      "トマト",
      "マヨネーズ",
    ],
  },
  {
    name: "チャプチェ",
    categoryName: "韓国料理",
    subCategoriesNames: ["麺類", "野菜"],
    ingredientsNames: ["粉冬瓜麺", "ほうれん草", "人参", "玉ねぎ", "しいたけ"],
  },
  {
    name: "ローストビーフ丼",
    categoryName: "和食",
    subCategoriesNames: ["丼物", "肉料理", "ご飯"],
    ingredientsNames: [
      "ローストビーフ",
      "ご飯",
      "玉ねぎ",
      "アボカド",
      "味付け海苔",
    ],
  },
  {
    name: "チキン南蛮",
    categoryName: "和食",
    subCategoriesNames: ["揚げ物", "酸っぱい"],
    ingredientsNames: ["鶏もも肉", "片栗粉", "卵", "しょうゆ", "米酢"],
  },
  {
    name: "ボロネーゼ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ", "肉料理"],
    ingredientsNames: ["スパゲッティ", "挽肉", "玉ねぎ", "トマト缶", "バジル"],
  },
  {
    name: "チキンステーキ",
    categoryName: "洋食",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: [
      "鶏もも肉",
      "バター",
      "ニンニク",
      "ローズマリー",
      "レモン汁",
    ],
  },
  {
    name: "エビチリ",
    categoryName: "中華",
    subCategoriesNames: ["海鮮", "辛い", "ご飯"],
    ingredientsNames: ["えび", "トマト", "玉ねぎ", "ピーマン", "唐辛子"],
  },
  {
    name: "トムヤムクン",
    categoryName: "アジアン",
    subCategoriesNames: ["スープ", "酸っぱい", "辛い"],
    ingredientsNames: ["海老", "トマト", "しめじ", "レモングラス", "唐辛子"],
  },
  {
    name: "クレープ",
    categoryName: "スイーツ",
    subCategoriesNames: ["甘い"],
    ingredientsNames: ["小麦粉", "卵", "牛乳", "砂糖"],
  },
  {
    name: "カルボナーラ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ", "ソース", "卵料理"],
    ingredientsNames: [
      "スパゲッティ",
      "ベーコン",
      "卵黄",
      "グラナ・パダーノ",
      "黒こしょう",
    ],
  },
  {
    name: "プチフール",
    categoryName: "スイーツ",
    subCategoriesNames: ["焼き菓子"],
    ingredientsNames: ["バター", "砂糖", "薄力粉"],
  },
  {
    name: "モンブラン",
    categoryName: "スイーツ",
    subCategoriesNames: ["洋菓子", "和洋菓子"],
    ingredientsNames: ["さつまいも", "砂糖", "生クリーム"],
  },
  {
    name: "餃子",
    categoryName: "中華",
    subCategoriesNames: ["肉料理", "揚げ物"],
    ingredientsNames: [
      "豚肉",
      "ニラ",
      "キャベツ",
      "生姜",
      "にんにく",
      "餃子の皮",
    ],
  },
  {
    name: "酢豚",
    categoryName: "中華",
    subCategoriesNames: ["肉料理", "甘酢料理"],
    ingredientsNames: [
      "豚肉",
      "ピーマン",
      "玉ねぎ",
      "パプリカ",
      "酢",
      "砂糖",
      "しょうゆ",
      "酒",
    ],
  },
  {
    name: "ホットケーキ",
    categoryName: "スイーツ",
    subCategoriesNames: ["焼き菓子"],
    ingredientsNames: ["薄力粉", "ベーキングパウダー", "卵", "砂糖", "牛乳"],
  },
  {
    name: "カツサンド",
    categoryName: "サンドイッチ",
    subCategoriesNames: ["揚げ物", "パン"],
    ingredientsNames: ["豚ロースカツ", "食パン", "レタス", "マヨネーズ"],
  },
  {
    name: "マカロニグラタン",
    categoryName: "洋食",
    subCategoriesNames: ["パスタ", "グラタン"],
    ingredientsNames: ["マカロニ", "牛乳", "バター", "小麦粉", "チーズ"],
  },
  {
    name: "ステーキ",
    categoryName: "洋食",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: ["牛肉", "塩", "コショウ", "バター"],
  },
  {
    name: "杏仁豆腐",
    categoryName: "スイーツ",
    subCategoriesNames: ["プリン", "和菓子"],
    ingredientsNames: ["豆乳", "砂糖", "寒天"],
  },
  {
    name: "焼肉",
    categoryName: "その他",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: ["牛肉", "豚肉", "鶏肉", "キムチ", "にんにく", "玉ねぎ"],
  },
  {
    name: "バーベキュー",
    categoryName: "その他",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: ["牛肉", "豚肉", "鶏肉", "ポテト", "トマト", "コーン"],
  },
  {
    name: "カキフライ",
    categoryName: "洋食",
    subCategoriesNames: ["揚げ物"],
    ingredientsNames: ["牡蠣", "パン粉", "卵"],
  },
  {
    name: "オムレツ",
    categoryName: "洋食",
    subCategoriesNames: ["卵料理"],
    ingredientsNames: ["卵", "玉ねぎ", "ハム"],
  },
  {
    name: "ラーメン",
    categoryName: "中華",
    subCategoriesNames: ["麺類"],
    ingredientsNames: ["豚肉", "メンマ", "ネギ", "味噌"],
  },
  {
    name: "餃子",
    categoryName: "中華",
    subCategoriesNames: ["揚げ物"],
    ingredientsNames: ["豚肉", "ニラ", "キャベツ", "餃子の皮"],
  },
  {
    name: "チャーハン",
    categoryName: "中華",
    subCategoriesNames: ["ご飯"],
    ingredientsNames: ["卵", "ハム", "玉ねぎ", "にんにく"],
  },
  {
    name: "トムヤムクン",
    categoryName: "アジアン",
    subCategoriesNames: ["スープ"],
    ingredientsNames: [
      "エビ",
      "タイムレモングラス",
      "トマト",
      "酸っぱい調味料",
    ],
  },
  {
    name: "サムギョプサル",
    categoryName: "韓国料理",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: ["豚肉", "キムチ", "レタス", "にんにく"],
  },
  {
    name: "カレーライス",
    categoryName: "その他",
    subCategoriesNames: ["ご飯"],
    ingredientsNames: ["牛肉", "玉ねぎ", "にんじん", "カレールー"],
  },
  {
    name: "タコス",
    categoryName: "アジアン",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: ["挽肉", "トマト", "玉ねぎ", "トルティーヤチップス"],
  },
  {
    name: "ビビンバ",
    categoryName: "韓国料理",
    subCategoriesNames: ["ご飯"],
    ingredientsNames: ["ご飯", "牛肉", "野菜", "キムチ"],
  },
  {
    name: "からあげ",
    categoryName: "和食",
    subCategoriesNames: ["揚げ物", "肉料理"],
    ingredientsNames: [
      "鶏肉",
      "片栗粉",
      "酒",
      "しょうゆ",
      "生姜",
      "にんにく",
      "ごま油",
    ],
  },
  {
    name: "とんかつ",
    categoryName: "和食",
    subCategoriesNames: ["揚げ物", "肉料理"],
    ingredientsNames: ["豚肉", "パン粉", "卵", "キャベツ", "トンカツソース"],
  },
  {
    name: "チャーハン",
    categoryName: "中華",
    subCategoriesNames: ["ご飯", "炒め物"],
    ingredientsNames: [
      "ご飯",
      "卵",
      "豚肉",
      "にんじん",
      "たまねぎ",
      "青ねぎ",
      "しょうゆ",
    ],
  },
  {
    name: "麻婆豆腐",
    categoryName: "中華",
    subCategoriesNames: ["麺類", "煮込み料理"],
    ingredientsNames: [
      "絹ごし豆腐",
      "挽肉",
      "豆板醤",
      "豆豉",
      "ニンニク",
      "ショウガ",
      "豆板醤",
      "鶏がらスープ",
      "醤油",
      "料理酒",
    ],
  },
  {
    name: "トマトパスタ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ"],
    ingredientsNames: [
      "パスタ",
      "ツナ缶",
      "トマト缶",
      "玉ねぎ",
      "にんにく",
      "バジル",
      "パルメザンチーズ",
    ],
  },
  {
    name: "ミートスパゲッティ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ"],
    ingredientsNames: [
      "パスタ",
      "ミンチ",
      "玉ねぎ",
      "にんにく",
      "トマト缶",
      "赤ワイン",
      "バジル",
      "パルメザンチーズ",
    ],
  },
  {
    name: "クリームパスタ",
    categoryName: "イタリアン",
    subCategoriesNames: ["パスタ"],
    ingredientsNames: [
      "パスタ",
      "ベーコン",
      "玉ねぎ",
      "生クリーム",
      "バター",
      "鶏ガラスープ",
      "パルメザンチーズ",
    ],
  },
  {
    name: "ハンバーグ",
    categoryName: "洋食",
    subCategoriesNames: ["肉料理"],
    ingredientsNames: [
      "牛肉",
      "玉ねぎ",
      "パン粉",
      "卵",
      "ケチャップ",
      "ウスターソース",
    ],
  },
  {
    name: "ラタトゥイユ",
    categoryName: "フレンチ",
    subCategoriesNames: ["野菜料理"],
    ingredientsNames: [
      "ズッキーニ",
      "ナス",
      "パプリカ",
      "トマト",
      "玉ねぎ",
      "にんにく",
      "バジル",
      "オリーブオイル",
    ],
  },
  {
    name: "ブイヤベース",
    categoryName: "フレンチ",
    subCategoriesNames: ["魚料理", "スープ"],
    ingredientsNames: [
      "タラ",
      "鮭",
      "ムール貝",
      "エビ",
      "トマト",
      "玉ねぎ",
      "ニンジン",
      "セロリ",
      "にんにく",
      "パセリ",
      "バジル",
      "オリーブオイル",
    ],
  },
  {
    name: "ボンゴレビアンコ",
    categoryName: "イタリアン",
    subCategoriesNames: ["麺料理", "海鮮料理"],
    ingredientsNames: [
      "スパゲッティ",
      "アサリ",
      "オリーブオイル",
      "にんにく",
      "唐辛子",
      "パセリ",
    ],
  },
  {
    name: "チキンティッカマサラ",
    categoryName: "インド",
    subCategoriesNames: ["鶏肉料理", "カレー"],
    ingredientsNames: [
      "鶏もも肉",
      "ヨーグルト",
      "ターメリック",
      "クミン",
      "コリアンダー",
      "カルダモン",
      "シナモン",
      "生姜",
      "にんにく",
      "トマト",
      "クリーム",
    ],
  },
  {
    name: "タンドリーチキン",
    categoryName: "インド",
    subCategoriesNames: ["鶏肉料理"],
    ingredientsNames: [
      "鶏もも肉",
      "ヨーグルト",
      "ターメリック",
      "クミン",
      "コリアンダー",
      "カルダモン",
      "シナモン",
      "生姜",
      "にんにく",
      "レモン汁",
    ],
  },
  {
    name: "マトンカレー",
    categoryName: "インド",
    subCategoriesNames: ["羊肉料理", "カレー"],
    ingredientsNames: [
      "マトン肉",
      "トマト",
      "玉ねぎ",
      "生姜",
      "にんにく",
      "唐辛子",
      "カルダモン",
      "クローブ",
      "シナモン",
      "クミン",
      "コリアンダー",
      "ターメリック",
    ],
  },
  {
    name: "バターチキンカレー",
    categoryName: "インド",
    subCategoriesNames: ["鶏肉料理", "カレー"],
    ingredientsNames: ["鶏もも肉", "トマト", "玉ねぎ"],
  },
];

const main = async () => {
  for (const d of data) {
    const dish = await prisma.dish.findUnique({
      where: {
        name: d.name,
      },
    });
    if (dish) {
      continue;
    }
    await prisma.dish.create({
      data: {
        name: d.name,
        category: {
          connectOrCreate: {
            where: {
              name: d.categoryName,
            },
            create: {
              name: d.categoryName,
            },
          },
        },
        subCategories: {
          connectOrCreate: d.subCategoriesNames.map((name) => ({
            where: {
              name,
            },
            create: {
              name,
            },
          })),
        },
        ingredients: {
          connectOrCreate: d.ingredientsNames.map((name) => ({
            where: {
              name,
            },
            create: {
              name,
            },
          })),
        },
      },
    });
  }
};

void main();
