import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <button className="btn">
          {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
        </button>
        <div className="">
          {data?.map((post) => (
            <div className="" key={post.id}>
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
