import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Avatar } from "@/components/Elements/Avatar";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        {user.isSignedIn ? (
          <>
            <SignOutButton>
              <button className="btn">Sign Out</button>
            </SignOutButton>
            <div className="">
              <Avatar size="xl" src={user.user?.profileImageUrl} />
            </div>
          </>
        ) : (
          <SignInButton>
            <button className="btn">Sign In</button>
          </SignInButton>
        )}
        <div className="">
          {data?.map((post) => (
            <div className="" key={post.id}>
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
